Update publish.yml
`rojo upload` seems to invalidate the cookie?

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -17,22 +17,22 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
-      - name: Test Roblox Login Tokens
-        shell: bash
-        run: |
-          if [ -z "${{ secrets.ROBLOSECURITY }}" ]; then
-            echo "No cookie found. Please set the ROBLOSECURITY secret."
-            exit 1
-          fi
+      # - name: Test Roblox Login Tokens
+      #   shell: bash
+      #   run: |
+      #     if [ -z "${{ secrets.ROBLOSECURITY }}" ]; then
+      #       echo "No cookie found. Please set the ROBLOSECURITY secret."
+      #       exit 1
+      #     fi
 
-          RBX_USERNAME=$(curl -s -X GET -H "Cookie: .ROBLOSECURITY=${{ secrets.ROBLOSECURITY }}" https://users.roblox.com/v1/users/authenticated | jq -r ".name")
+      #     RBX_USERNAME=$(curl -s -X GET -H "Cookie: .ROBLOSECURITY=${{ secrets.ROBLOSECURITY }}" https://users.roblox.com/v1/users/authenticated | jq -r ".name")
 
-          if [ -z "$RBX_USERNAME" ]; then
-            echo "ROBLOSECURITY is invalid or expired. Please reset the ROBLOSECURITY secret."
-            exit 1
-          fi
+      #     if [ -z "$RBX_USERNAME" ]; then
+      #       echo "ROBLOSECURITY is invalid or expired. Please reset the ROBLOSECURITY secret."
+      #       exit 1
+      #     fi
 
-          echo "Logged in as $RBX_USERNAME."
+      #     echo "Logged in as $RBX_USERNAME."
 
       - name: Setup Node LTS
         uses: actions/setup-node@v2
@@ -59,12 +59,13 @@ jobs:
         run: |
           find . -name "*.spec.lua" -delete
 
-      - name: Publish to Roblox
-        if: ${{ github.event.release.prerelease == false }}
-        shell: bash
-        run: rojo upload default.project.json --asset_id $ASSET_ID_STABLE --cookie "${{ secrets.ROBLOSECURITY }}"
+      # - name: Publish to Roblox
+      #   if: ${{ github.event.release.prerelease == false }}
+      #   shell: bash
+      #   run: rojo upload default.project.json --asset_id $ASSET_ID_STABLE --cookie "${{ secrets.ROBLOSECURITY }}"
 
       - name: Publish to Wally
+        if: ${{ github.event.release.prerelease == false }}
         env:
           WALLY_TOKEN: ${{ secrets.WALLY_TOKEN }}
         run: |
@@ -73,6 +74,7 @@ jobs:
           wally publish
 
       - name: Publish to NPM
+        if: ${{ github.event.release.prerelease == false }}
         uses: JS-DevTools/npm-publish@v1
         with:
           token: ${{ secrets.NPM_TOKEN }}
